"""add ratings table

Revision ID: 597d01620d0d
Revises: c6169388f909
Create Date: 2025-08-28 03:56:13.521864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '597d01620d0d'
down_revision: Union[str, Sequence[str], None] = 'c6169388f909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('ix_ratings_movie_id', 'ratings', ['movie_id'], unique=False)
    op.create_unique_constraint('uix_user_movie', 'ratings', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_movie', 'ratings', type_='unique')
    op.drop_index('ix_ratings_movie_id', table_name='ratings')
    op.alter_column('ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ratings', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
